### ISSUE TITLE
BTC address input box doesn't work

### ISSUE THREAD

**Issue by larrysalibra** [friedger/stacks-swaps#4]
Hi Friedger! I was trying to do a STX/BTC catamaran swap at https://www.catamaranswaps.org/stx

Typing or pasting the bitcoin address into the bitcoin recipient address input box doesn't work on Chrome Version 93.0.4577.82 (Official Build) (arm64) and Firefox 92.0 (64 bit) on macOS 11.6.

<img width="780" alt="Screen Shot 2021-09-17 at 1 40 11 PM" src="https://user-images.githubusercontent.com/597182/133730457-eca2cdce-a860-4286-8e4c-8b9e03b01993.png">

I'm using Hiro Wallet v2.17.0.

**Comment by friedger** [comment]
Thank you for reporting!
Has been fixed in https://github.com/friedger/stacks-swaps/commit/5c93d84a6ce3018adf079d0a4babec375b2321fb
