### ISSUE TITLE
🐞[BUG] "Cancel button" does not show after 100 blocks

### ISSUE THREAD

**Issue by criadoperez** [friedger/stacks-swaps#6]
**Describe the bug**
"Cancel button" does not show after 100 blocks

**Screenshots**
![image](https://user-images.githubusercontent.com/8580472/173603120-fe162348-2f89-4789-897f-cd0c6f4b2195.png)

**Comment by friedger** [comment]
This is now fixed.
Any user can cancel it because we don't have the stx address of the creator of the swap.

**Comment by friedger** [comment]
![Screenshot from 2022-06-14 23-14-34](https://user-images.githubusercontent.com/1449049/173690224-1e7917d1-8626-4af6-afe6-b3c4656f14e2.png)

**Comment by criadoperez** [comment]
Thank you for the quick fix @friedger !
I confirm I could cancel with no problem.
